### ISSUE TITLE
Update Harvester to not assume herbs and send 'ab herbs'

### ISSUE THREAD

**Issue by mikepmanning** [m-mf/m-mf#10]
Currently the Harvester plugin assumes that the user has the Herbs skillset and sends AB herbs upon start.

Should change this to use GMCP to check the skillset

**Comment by toadhats** [comment]
I was wondering, why does it include harvesting when you build the system for a class that doesn't have herbs? It seems to have done so for me, anyway.

**Comment by mikepmanning** [comment]
that's just the way it's setup now, I think when Vadi moved it to open source, he just included all add-ons on all systems, so it's a change that can be added to only include it on systems that can actually use Herbs

**Comment by JCalvinL** [comment]
Think ab herbs check should not be necessary? We can probably make it run a
gmcp check for players who have the skill or not. Much more silent.

**Comment by mikepmanning** [comment]
I added in functionality to fix this

if gmcp is enabled and populated - it will check the skill list behind the scenes and record all the relevant information. 

if gmcp is not enabled - it will still check ab herbs, but not until you actually log in.
