### ISSUE TITLE
Classflexing

### ISSUE THREAD

**Issue by mikepmanning** [m-mf/m-mf#11]
Look into adding a way to allow someone to have multiple classes without using allclasse system

Allclass system can achieve this, but can maybe add a solution that allows multiple classes

**Comment by JCalvinL** [comment]
We can include all classes no problem. System would just need to do a gmcp
check for skills at login to know which skills should be active. If
players classflex or skillflex. Can have a trigger or an alias to recheck
their gmcp stats for abilities active.

**Comment by mikepmanning** [comment]
If we pursued the route of a gmcp check each time you logged in, would we need to maintain separate class systems, or just use the allclass system for everyone and have it load the skills based on the gmcp check? How would that effect performance on logging in etc?

**Comment by JCalvinL** [comment]
I do it for MKO. There isn't any lag time when loading up the external
files when logging in. But m&m is way different and Lusternia has twice as
many skillsets. So there isn't any guarantee that there won't be
performance issues at startup.

**Comment by vadi2** [comment]
Making allclass system handle which things should be enabled/disabled via gmcp would be better. mmconfigs would need to be toggled (succor, etc...) and the hidelist would need to be auto-adjusted appropriately.

**Comment by ronh3** [comment]
So, just wrote a thing to do this 'cause I was tired of setting this every time I change skills around and the like.  The following is how I did it, though I'm sure there are more elegant solutions. This way kills all groups except for enchantments and general, then enables the groups that show up in gmcp.Char.Skills.Groups. I'm too lazy to get Git running myself, but this should be simple to hack up and add in as desired.

KillSkills = {"Paradigmatics", "Nihilism", "Stealth", "Ecology", "Cosmic", "Aeonics", "Aquamancy", "Nekotai", "Hexes", "Geomancy", "Pyromancy", "Athletics", "Transmology", "Tahtetso", "Astrology", "Acrobatics", "Music", "Glamours", "Moon", "Starhymn", "Shofangi", "Psionics", "Illusions", "Psychometabolism", "Tarot", "Telepathy", "Stag", "Rituals", "Night", "Highmagic", "Sacraments", "Dreamweaving", "Ninjakari", "Healing", "Druidry", "Ascendance", "Tracking", "Elementalism", "Celestialism", "Wildarrane", "Necromancy", "Runes", "Hunting", "Knighthood", "Telekinesis", "Phantasms", "Aeromancy", "Nature", "Crow", "Lowmagic", "Totems"}

for i,v in pairs(KillSkills) do
    mm.ignoreskill((KillSkills[i]), true, false)
end

for k,v in pairs(gmcp.Char.Skills.Groups) do
    mm.ignoreskill((gmcp.Char.Skills.Groups[k].name), false, false)
end

**Comment by ronh3** [comment]
Played around with this a bit more. Made a multi line login trigger, gave it a delta of twenty-five lines, had it match against the password is correct, and then the return isPrompt() function. Works like a charm. Pic is a picture of my setup.

https://gyazo.com/d640956124ab965611405e093fdafb08

**Comment by vadi2** [comment]
There's a gmcp event you can use for login as well.

**Comment by ronh3** [comment]
You know, I didn't think to look for that. Would likely be far more elegant
to do it that way. At best, I can kludge things together until they manage
to somehow work (see my uis).

**Comment by mikepmanning** [comment]
Added scripting and a new gmcp event for when the Skills.Groups is called

This adds a new table under mm.me called activeskills. When a skill is forgotten, or Ab is called (right now it doesn't send a update on activating a skill) this function will check the groups and will inactivate any previously activated skills and activate any previously inactivated skills. It'll raise an event for each scenario as well for people to hook on and change defs, configs etc.

I also added a config option (conf.autohide) to auto hide inactive skillsets and show active ones. I figured it was best to have this as a config option so people can opt in in case they have previously set things up and don't want to mess with it.

Just added documentation for the events and the config, should be good to go in the next release

**Comment by mikepmanning** [comment]
Closing this, I don't think there's really anything else that can be added to account for classflexing. The new events and config option will make it easy to change defs, account for activeskills, change config options if needed and even allow people to play multiple characters on the same profile I believe (if they're using the allclass system).
