### ISSUE TITLE
Aeon curing seems to prioritize anorexia over asthma

### ISSUE THREAD

**Issue by malarious** [m-mf/m-mf#12]
Based on a log I saw recently having aeon and asthma should lead to asthma being cured, but the system attempts to cure anorexia (from malefact gem) first instead, leading to getting stuck.

**Comment by mikepmanning** [comment]
That's a priority issue,  not a system issue.  User priorities are 100%
adjustable and should take care of that issue

**Comment by vadi2** [comment]
Adding the log here would help - chances are the systems triggers didn't pick up the anorexia line. The symptom triggers might need looking at as well, as they should pick up when a cure fails.

**Comment by mikepmanning** [comment]
Can't confirm this, testing with prios has shown that this cures in the correct order, closing for now, will reopen with addition of logs
