### ISSUE TITLE
namedb help not working

### ISSUE THREAD

**Issue by Sairys** [m-mf/m-mf#14]
It looks like the commands ndb and ndblong aren't working at the moment.

The aliases appear to function as when I add echo("ping") to them the echo works, but no other info comes up.
![image](https://cloud.githubusercontent.com/assets/14342844/9974547/1c12178e-5ed7-11e5-874f-20affbd4f6ed.png)

**Comment by CaPensiPraxis** [comment]
I think this is because they rely on the package installed including the character's name, as it was in M&M. Should be easy to fix.

**Comment by keneanung** [comment]
Svof had a similar issue. See https://github.com/svof/svof/commit/2668c56d6d8a813aa140606d36855652ca591f33 for the fix there.

**Comment by mikepmanning** [comment]
made changes to fix this in m&m ndb.xml - should be good on next release
