### ISSUE TITLE
Should support multiple profiles from one fork

### ISSUE THREAD

**Issue by CaPensiPraxis** [m-mf/m-mf#16]
Building a new profile to use/test/develop M&MF on a new profile with a different class edits the 'own m&mf' folder for previous files, changing their loadout. This could potentially be solved alongside the classflexing issue.

**Comment by mikepmanning** [comment]
Easy answer to this is to use 'allclasses' in your own m&mf folder so you don't have to worry about individual classes. 

You'll have to add some scripting to ignore skillsets, but should be doable. It's going to be easier to handle it this way rather than changing how it loads m&m.

**Comment by mikepmanning** [comment]
I'm going to close this - while I understand the premise and the desire to want to load multiple profiles from one m&m class profile - I can't think of a good way to handle that outside using the allclasses output. The second best bet is to re-generate the m&m file when switching classes to update the output file. 

But basically, not going to fix this at this point in time.

**Comment by ronh3** [comment]
Tbh, get auto detecting available skills in, use my kludge to update defs,
and have the system check after getting the initial gmcp skill info to set
mmconfig stuff automatically... I'll look and see what I can do with all
that from the user end.
