### ISSUE TITLE
Athletics-Regeneration not tracked correctly

### ISSUE THREAD

**Issue by markrae** [m-mf/m-mf#18]
Athletics - Regeneration is not being tracked accurately. I'm using the Sentinel.m-mf.v3.zip package. Below is a short log that shows the problem.

(m&mf): Athletics defences:
[ ] consciousness          [ ] flex                   [ ] surge
[X] boosting               [ ] regeneration           [ ] breathing
[ ] resistance             [ ] weathering             [ ] immunity
[ ] adrenaline             [X] vitality               [ ] constitution
(m&mf): Additional defences:
[X] domoth major life  
You have recovered equilibrium. (0.649s)
7500h, 5100m, 5900e, 10p elrx-(regeneration on)
You are already regenerating.
7500h, 5100m, 5900e, 10p elrx-

**Comment by markrae** [comment]
I realized that defs was saying I had Athletics-Boosting up, even though I haven't learned that yet. Turning regeneration off caused defs to no longer say that boosting was active. Hypothesis: regeneration and boosting are being tracked in each other's place.
Can someone who does know boosting confirm if switching boosting on and off affects defs tracking of regeneration?

**Comment by markrae** [comment]
I've located some of the lines that seem to be the source of this issue.

https://github.com/m-mf/m-mf/blob/master/raw-mm.defs.lua#L1719
The correct line for regeneration is "You are regenerating lost health." not "Your regeneration is boosted."

https://github.com/m-mf/m-mf/blob/master/raw-mm.defs.lua#L2565
Again, "You are regenerating lost health." belongs to regeneration rather than boosting, though it appears that regeneration doesn't have its own entry. While we're at it, the tooltip could be updated: BodyScan reports the non-boosted regeneration to be 2/8 to health; there's no longer a willpower drain as willpower is deprecated.

Hypothesis: having boosting active changes and overrides the def line for regeneration, which is why the system is currently set up this way. (Again, I wouldn't know since I haven't learned up to boosting yet.)

**Comment by ronh3** [comment]
Can confirm.  Regeneration on causes boosting to be lit up.  Boosting causes regeneration to be up.  Turning off regeneration causes both to be unticked.

**Comment by mikepmanning** [comment]
This should be fixed in the next release (v7)
