### ISSUE TITLE
Enable automatic updates

### ISSUE THREAD

**Issue by vadi2** [m-mf/m-mf#2]
Enable automatic updates from Github like m&m used to have them before. Automatic updates are essential, as updating manually makes people lag behind.

**Comment by mikepmanning** [comment]
Checking out svof - they accomplished this by someone hosting the new releases on their server.

Does anyone have a server they can volunteer to host this on?

**Comment by ronh3** [comment]
Very tempted to purchase some hosting and m&m-f.com

Since Lusternia/IRE bought out Vadi, perhaps Estarra should be contacted
about providing a directory on the Lusternia.com domain.

**Comment by mikepmanning** [comment]
That's a good idea, I'll send an email to her tonight to see if there is anything we can do

**Comment by ronh3** [comment]
If not, let me know what domain you'd like and I'll pick it up for a year.

**Comment by ronh3** [comment]
Any movement on this?

**Comment by steingrim** [comment]
Isn't Vadim saying that it could be done though github? Or was he just hoping it was possible? Or did he not mean 'from Github'?

**Comment by mikepmanning** [comment]
Can't use Github because mudlet doesn't support https - need a site that supports http

**Comment by ronh3** [comment]
Estarra ever respond about it being hosted directly on Lusternia.com?

**Comment by mikepmanning** [comment]
@keneanung - I was talking to someone about using github pages to host the system up. They suggested that we could possibly do the following (I'm just c/p what he put)

> Prod him, ask if he can handle it. It should be as easy as adding the following  after line 17 to travis.sh
> mkdir release
> cp ../../../output/*.zip release/
> _>
> And generating a manifest file for the version, of course, however that was handled with the old M&M stuff
> (If it's just a file with the version number, you're pretty much set. Just cat it to a file there)(edited)
> At that point, you can just grab anything you need from
> http://m-mf.github.io/m-mf/release/

Will something like this work? I honestly don't understand this whole process a lot, so any input would be great. Thanks

**Comment by vadi2** [comment]
Github will only serve over HTTPS and Mudlet 2.x can't download over HTTPS.

**Comment by ndguarino** [comment]
@vadi2 Github Pages supports HTTP and uses it by default.
See: http://m-mf.github.io/m-mf/

**Comment by keneanung** [comment]
@siddister This approach may work. I'll go ahead and try this when I got some time on my hands (which is hopefully soonish).

**Comment by mikepmanning** [comment]
No worries @keneanung - thanks for taking a look

**Comment by mikepmanning** [comment]
Closing this because it has been in place since v12 or so and has been working
