### ISSUE TITLE
Add couple of def lines

### ISSUE THREAD

**Issue by mikepmanning** [m-mf/m-mf#20]
Need to add in Waterbreathing defline

Levitation from gnomish ballon

**Comment by mikepmanning** [comment]
Waterbreathing defline has been added - should be released in version 4.

**Comment by mikepmanning** [comment]
The other deflines have been updated in the latest push

Only issue is that sometimes the def pops up with a time rather than 'indefinite'

**Comment by ronh3** [comment]
Couple of missing defs that I have.

You have a potent gestalt composed of nine ikons. - Dramatics
Your influencing is buffed by hair! Glorious hair! - Curio
You will discharge a psychic lash from a powerful artifact on those who scry. - Artifact, duplicates psymet mindfield

Wondercornucopia lines
Your balance has been enhanced through fine food.
Your health has been enhanced through fine food.
Your ego has been enhanced through fine food.
Your equilibrium has been enhanced through fine food.
Your damage has been enhanced through fine food.
Your mana has been enhanced through fine food.
Your resistance has been enhanced through fine food.

**Comment by ronh3** [comment]
Missing Pyrochem defs.
(number of months varies, obviously)

You have a pyroaugmentorius gadget for another 10 months. (1/8 fire damage buff)
You have electrical dampeners lasting another 10 months. (1/8 electrical damage resist)
You have cool thermal pumps which will last 10 months. (10% damage from ablaze, cure one aff per ablaze tic)
You have haze-piercing goggles for another 10 months. (see obscured exits)
You are surrounded by a haze of scorching smoke for another 10 months. (20% chance to knock attackers off bal for 1s)
You are surrounded by a haze of hallucinatory smoke for another 10 months. (20% to cause hallucinations to attackers)
You are surrounded by a haze of pyretic smoke for another 10 months. (20% chance to cause addiction to attackers)
You are surrounded by a haze of fevered smoke for another 10 months. (20% chance to cause amnesia to attackers)
You rub your hands up and down your arms, lighting small fires that quickly spread and cover your entire body before quickly dying out. (fireproof, 1/8 fire damage resist, can wander fire plane without being moved)

**Comment by mikepmanning** [comment]
The pyrochem defs are already in it looks like - are they not registering or something?

**Comment by ronh3** [comment]
Not at all, which I found odd. I'll try it on a work machine in a bit.

**Comment by mikepmanning** [comment]
1) Added wondercorn defs
     all defs are 'wondercorn' followed by the the buff (hp,mp,ego,dam,res,bal,eq)
     they are added to general defs, so you can use defup/keepup with them

2) Added redgenies/bluegenies/yellowgenies defs
    Previous versions had curiohp/mp/ego as just a defline - changed the name (to be more fitting) and enabled use on defup/keepup

3) added deflines for gestalt and hair curios, and a few poteen buff lines. These are just defline, no defup/keepup enabled for them.

**Comment by mikepmanning** [comment]
Pyrochem (and all the chem/woods) were not included on the allclass system. Defs are in place and they're included now

**Comment by mikepmanning** [comment]
Additionally - All defs listed in this issue have been added/fixed.  - closing this for now
