### ISSUE TITLE
Issue with tendon?

### ISSUE THREAD

**Issue by Taevyn** [m-mf/m-mf#22]
The fight:
https://ada-young.appspot.com/pastebin/e6d726e7

The error:
[ERROR:] object:<Tendon> function:<Trigger1765>
         <....config\mudlet\profiles\Taevyn/Tahtetso m&m/m&m:44436: attempt to call field 'simpletendonunknown' (a nil value)>

**Comment by GreyFacade** [comment]
mm.valid.simpletendonunknown is only thrown here by mm.valid.tendon_springup and shouldn't pass the trigger checks if you know you have left/right tendon on the springup line. I figure you dropped tendon somewhere?

Also, small typo in afftranslation: ["righttendron"] -> ["righttendon"]

I imagine the potential fix is:
Add "tendonunknown" to the for loop for declaring simplevalids.

**Comment by mikepmanning** [comment]
with the warrior change, this is no longer an issue
