### ISSUE TITLE
Ice balance curing

### ISSUE THREAD

**Issue by mikepmanning** [m-mf/m-mf#24]
I've started working on adding ice balance - just wanted a place to document things so I know what to work on., what's missing etc.

General
- [x]  Affs added to dict
- [x] Wounds added to dict
- [x] Lower failsafe delay threshold (dependent on wounds?)
- [ ] Add in GMCP info for wounds and affs
- [x] Add in stance/parry interaction with new wound values
- [x] Include a logical initial prio order for ice (it's random at the moment)
- [ ] Make affliction specific functions to include relevant information (wounds, bleeding, affs etc) 
- [x] Add in bruising mechanics

PB
- [x] PB trigger lines added
- [x] Account for bleeder combatstyle (less wounds, more bleed) - current triggers are for not bleeder combatstyle
- [x] Add Bleeder combatstyle in as a def
- [ ] Opengut for PB doesn't work currently, add it in when it does.
- [x] Account for Twist addition to bleeding + damage

BM
- [x] Add in BM trigger lines
- [ ] Add in remiss triggers (broken at the moment)

AL
- [x] Add in AL trigger lines
- [x] Add in Berserker combatstyle as a def

BC
- [x] Add in BC trigger lines
- [x] Account for Bludgeoner combatstyle
- [x] Bludgeoner def
- [x] Smashleg adding more bruising depending on wounds

Cav
- [x] Add in Cav trigger lines

**Comment by vadi2** [comment]
You can actually have todo lists - try it out: https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments

**Comment by mikepmanning** [comment]
This is pretty much taken care of, there are probably some issues that I haven't hit during my testing, but those can be addressed in a separate issue. The missing stuff can be added as needed. 

As for GMCP - that can be added for all afflictions in general.
