### ISSUE TITLE
NDB not echoing out Celest color

### ISSUE THREAD

**Issue by ronh3** [m-mf/m-mf#38]
When you ask NDB for the color for a Celest person, it doesn't output it. Fix is as follows.

For the people tracker, there's an error that occurs with people from New Celest. You'll need to go into scripts, yourname m&m, ndb, ndb.api and find the line:
if city == "" or not city then city = false else city = city:lower() end -- known rogues are returned as ""
Add the following below that line:
if city=="new celest" then city="newcelest" end

**Comment by mikepmanning** [comment]
fixed - will be out in next release
