### ISSUE TITLE
Change m&mf documentation theme

### ISSUE THREAD

**Issue by vadi2** [m-mf/m-mf#4]
m&mf documentation should use a different theme from m&m, to make it more intuitive to differentiate the two.

**Comment by mikepmanning** [comment]
m&mf documentation is now hosted on github - there is a link on the readme that brings you to it so it's easy to find. 

What we can do is potentially add an alias in game that brings you to the website as well

**Comment by mikepmanning** [comment]
added an alias, will be released on v19

I think the theme is ok, closing for now
