### ISSUE TITLE
Eating merbloom instead of using Insomnia skill

### ISSUE THREAD

**Issue by Savrax** [m-mf/m-mf#70]
After the changes detailed in ANNOUNCE 2666, the system will eat merbloom instead of using the insomnia skill to keepup insomnia, even if I have enough mana and mmconfig insomnia is active.

My suspicion is the fact that willpower is no longer sent via GMCP, and the system may check on this before determining whether to use merbloom or insomnia.

EDIT: To add to this, the system will also eat chervil instead of clot.  There may be other willpower/mana related checks at play here.

**Comment by mikepmanning** [comment]
fixed - in v24
